### ISSUE TITLE
Delegar gastos de 2022 y monitorear

### ISSUE THREAD

**Issue by AlexandraChen** [Carodlg/velo-ops#115]
# JTBD
- Crear instrucciones claras y delegarlas

Deliverable de los colaboradores:
- Verificar gastos: si fueron facturados o no
- Cambiar estatus a los gastos o facturar

## Intro
- Fecha límite: Miércoles, 12 de octubre
- Propósito: Verificar si los gastos de los casos han sido facturados y cobrados al cliente.

## Deliverable
- Ir al Google Sheet https://docs.google.com/spreadsheets/d/1vOP0EMjXB5mUHbBWkE86WWux9hIcUcVG/edit?usp=sharing&ouid=104356601076796695491&rtpof=true&sd=true
- Ir a la pestaña asignada con tu nombre y darle una revisada
- Ir a Cases y buscar el caso: revisar los gastos cargados del Google Sheet y verificar si fue facturado en la factura correspondiente al caso.
  - Si el gasto fue facturado y cobrado:
    - Verificar el estatus del gastos en Cases.
    - Si el estatus de la factura es no facturado, cambiarle el estatus a facturado.
    - Ir a Google Sheets y actualizar el número de factura en la columna I 
  - Si hay gastos que no han sido facturados:
    - Ir al Google Sheet y actualizar la columna H (Facturado sí/no) con un no.

**Comment by AlexandraChen** [comment]
@adrianagrimaldo @carodlg instrucciones y deliverables ready.

@adrianagrimaldo: una vez que envíes esta información, asegúrate de que también lo menciones en vivo, puede ser durante un standup. Y mueves este ticket a la columna de Review (para que puedas monitorear el avance)

**Comment by AlexandraChen** [comment]
@adrianagrimaldo @carodlg instrucciones y deliverables ready.

@adrianagrimaldo: una vez que envíes esta información, asegúrate de que también lo menciones en vivo, puede ser durante un standup. Y mueves este ticket a la columna de Review (para que puedas monitorear el avance)

**Comment by adrianagrimaldo** [comment]
Delegado.
