### ISSUE TITLE
Enviar/definir: Horarios y Formas de trabajo al equipo

### ISSUE THREAD

**Issue by AlexandraChen** [Carodlg/velo-ops#125]
Follow up del ticket #110 
- [x] CAH: Crear un Google Sheet dentro del a carpeta de HR > Organización en Google Drive (https://drive.google.com/drive/folders/1X6VY-uE6m_hGPBtM3TiOB5NClWlwUYMT)  para definir horario seleccionado por cada colaborador
  - [x] CAH: Comunicar instrucción de selección de horarios a los colaboradores y asegurar que esté lleno el Google Sheet.
    - [x] CAH: Una vez que esté listo, comunicar el horario a todos en Veló
- [x] CAH: enviar documento final de la presentación de Formas de Trabajo.
  - [x] Duplicar archivo original (que sólo lo ve la gerencia) y editarlo para que sea público a todo Veló.
  - [x] Enviarlo al resto de los colaboradores.
  - [ ] CAH: Presentar forma de comunicación cliente interno y externo.

**Comment by adrianagrimaldo** [comment]
Google Sheet enviado

**Comment by Carodlg** [comment]
@adrianagrimaldo Aquí te paso el link del documento de las reglas para compartir (debes darle acceso al equipo en el documento) y comunicar a la gente:
https://drive.google.com/drive/folders/1WxtbULbdFFTul36frdMTA04JMK3sH9KO

**Comment by adrianagrimaldo** [comment]
Listo, enviado y comunicado.
