### ISSUE TITLE
Proceso de quick weekly review

### ISSUE THREAD

**Issue by AlexandraChen** [Carodlg/velo-ops#138]
- AG quiero asegurarme de que el equipo está realmente haciendo lo que ellos ponen en su board que están haciendo y cerrando

# Summary
https://docs.google.com/document/d/1MYuUZFyJSia_R60Fi6sFiFFY8Q64fuGWfCbLWSHZ-7Y/edit

**Comment by AlexandraChen** [comment]
@carodlg aquí puedes ver el proyecto que AG estará arrancando la próxima semana con el personal —> https://docs.google.com/document/d/1MYuUZFyJSia_R60Fi6sFiFFY8Q64fuGWfCbLWSHZ-7Y/edit

**Comment by AlexandraChen** [comment]
@carodlg aquí puedes ver el proyecto que AG estará arrancando la próxima semana con el personal —> https://docs.google.com/document/d/1MYuUZFyJSia_R60Fi6sFiFFY8Q64fuGWfCbLWSHZ-7Y/edit

**Comment by Carodlg** [comment]
@adrianagrimaldo @AlexandraChen excelente muy bien montado 👏🏻
